#!/bin/bash

## sw-osbox-bin
## JerryHopper - hopper.jerry@gmail.com

if [ "$1" == "getssl" ];then
  crt="https://api.surfwijzer.nl/localssl/ssl.dockbox.nl/ssl.dockbox.nl.crt"
  key="https://api.surfwijzer.nl/localssl/ssl.dockbox.nl/ssl.dockbox.nl.key"
  dstdir="/etc/osbox/.ssl"

  if [ -d $dstdir ];then
      mkdir -p $dstdir
  fi
  wget $crt $dstdir
  wget $key $dstdir
fi


####################################################################################################
if [ "$1" == "update" ]; then

  if [ "$2" == "latest" ];then
    if [ ! -f /etc/osbox/.dev ];then
        touch /etc/osbox/.dev
    fi
  fi
  if [ "$2" == "stable" ];then
    if [ -f /etc/osbox/.dev ];then
        rm -f /etc/osbox/.dev
    fi
  fi
  if [ "$2" == "?" ] || [ "$2" == "help" ];then
    echo "Usage: "
    echo "  osbox update  - Updates the application using current stable/latest setting"
    echo "  osbox update latest  - resets to stable updates and runs update."
    echo "  osbox update stable  - resets to latest unstable updates and runs update."
    echo "  osbox update ?/help  - this message."

    exit
  fi
  bash /usr/local/osbox/bin/update.sh
  bash /usr/local/osbox/project/sw-osbox-core/src/sh/database/update.sh
  #returnedstatus $? "success" "fail"
  systemctl daemon-reload
  exit
fi


####################################################################################################
## Run OSBOX core functionality.
if [ -f /usr/local/osbox/project/sw-osbox-core/osbox.sh ];then
  bash /usr/local/osbox/project/sw-osbox-core/osbox.sh "$@"
fi
