#!/bin/bash

# osbox install function

if [ "$1" == "installservice" ]; then
  if [ "$2" == "enable" ]; then
    if [ -f /etc/systemd/system/osbox.service ]; then
        rm -rf /etc/systemd/system/osbox.service
    fi
    # Enable the installer service
    ln -s /usr/local/osbox/lib/systemd/osbox.service /etc/systemd/system/osbox.service
    systemctl enable osbox.service
    exit;
  fi
  if [ "$2" == "disable" ]; then
    if [ -f /etc/systemd/system/osbox.service ]; then
        rm -rf /etc/systemd/system/osbox.service
    fi
    # Enable the installer service
    systemctl daemon-reload
    exit;
  fi
  echo "Usage: "
  echo "  osbox installservice enable  - Enables the installerservice"
  echo "  osbox installservice disable - Disables the installerservice"
  exit
fi


if [ "$1" == "reset" ]; then
  if [ "$2" == "version" ]; then
    rm -f /etc/osbox/.osbox.bin.version
    rm -f /etc/osbox/.osbox.core.version
    bash /usr/local/osbox/bin/update.sh
  fi
  if [ "$2" == "database" ]; then
    rm -f /etc/osbox/osbox.db
    bash /usr/local/osbox/bin/update.sh
  fi
  if [ "$2" == "all" ]; then
    bash /usr/local/osbox/bin/update.sh
  fi
  #returnedstatus $? "success" "fail"
  echo "Usage: "
  echo "  osbox reset version  - resets the version and  runs update."
  echo "  osbox reset database - removes the database and runs update."
  exit
fi

if [ "$1" == "update" ]; then
  bash /usr/local/osbox/bin/update.sh
  #returnedstatus $? "success" "fail"
  exit
fi


if [ -f /usr/local/osbox/project/sw-osbox-core/osbox.sh ];then
  bash /usr/local/osbox/project/sw-osbox-core/osbox.sh $1 $2 $3 $4 $5 $6
fi





